// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const DeviceLog = __t.object("DeviceLog", {
  id: __t.i32(),
  deviceId: __t.string(),
  insertedAt: __t.u64(),
});
export type DeviceLog = __Infer<typeof DeviceLog>;

